services:
  - type: web
    name: mahligai-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DB_URL
        value: postgresql://postgres.voehxdnuekfdycyrkfmu:110102Januari!@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true
