services:
  - type: web
    name: mahligai-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DB_URL
        value: postgresql://postgres:110102Jan!@db.voehxdnuekfdycyrkfmu.supabase.co:5432/postgres
